name: main

on: [push]

jobs:
  publish:
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # 4.1.0

      - name: Install .NET
        uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # 3.2.0
        with:
          dotnet-version: 8.0.x

      - name: Publish (CLI)
        run: dotnet publish DiscordChatExporter.Cli/ -o DiscordChatExporter.Cli/bin/Publish/ --configuration Release

      - name: Upload artifacts (CLI)
        uses: actions/upload-artifact@v3
        with:
          name: DiscordChatExporter.Cli
          path: DiscordChatExporter.Cli/bin/Publish/

  deploy:
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # 3.0.2
        with:
          name: ${{ matrix.app }}
          path: ${{ matrix.app }}/

      - name: Create package (CLI)
        run: Compress-Archive -Path DiscordChatExporter.Cli/* -DestinationPath DiscordChatExporter.Cli.zip -Force
        shell: pwsh

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            DiscordChatExporter.Cli.zip

  notify:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get release version
        id: get_version
        uses: dawidd6/action-get-tag@v1

      - name: Notify Discord
        uses: satak/webrequest-action@v1.2.4
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          headers: |
            {
              "ContentType": "application/json; charset=UTF-8"
            }
          payload: |
            {
              "content": "**DiscordChatExporter** new version released!\nVersion: `${{ steps.get_version.outputs.tag }}`>"
            }
